### ISSUE TITLE
"Gefilteter Datensatz" can not be exported on the BfR server.

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/zoonotify-api#122]
@MicheleK17 commented on [Thu Sep 30 2021](https://github.com/SiLeBAT/zoonotify-client/issues/357)

The filtered isolate endpoint is not available. 
Example: /v1/isolate/microorganism=CARBA-E.+coli

**Comment by dptolle** [comment]
@MicheleK17 As discussed, the endpoint URL may be incorrect in the client

**Comment by MicheleK17** [comment]
Done. Correction of the URL in ticket #309.
