### ISSUE TITLE
As a User I would like to be able to contact zoonotify-support via the 'Problem Melden' button 

### ISSUE THREAD

**Issue by MicheleK17** [SiLeBAT/zoonotify-api#15]
Retrieve the support-email address from the /info endpoint and add it into the relevant HTML Element

**Comment by dptolle** [comment]
Issue moved to [SiLeBAT/zoonotify-client #245](https://github.com/SiLeBAT/zoonotify-client/issues/245) via [**ZenHub**](https://www.zenhub.com/)
