### ISSUE TITLE
As a User I would like to have all characteristics diplayed in the downloaded dataset

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/zoonotify-api#154]

**Comment by MicheleK17** [comment]
Isolate endpoint returns empty object (no information about e.g. serovar)
- http://localhost:3000/v1/isolate?microorganism=CARBA-E.+coli
- http://localhost:3000/v1/isolate?microorganism=Salmonella+spp.

**Comment by MicheleK17** [comment]
If selecting more than one subfilter, the endpoint returns an empty list.

**Comment by MicheleK17** [comment]
v1/isolate?microorganism=Campylobacter+spp.&microorganism=Enterococcus+spp.&microorganism=STEC&microorganism=Salmonella+spp.&serovar=S.Abony

- returns 9858 counted isolates 
- but, only 5 Salmonella-isolates are shown in the isolate-endpoint.
