### ISSUE TITLE
Expose the header using Access-Control-Expose-Headers to calculate the export process in the FE

### ISSUE THREAD

**Issue by MicheleK17** [SiLeBAT/zoonotify-api#163]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Length
https://stackoverflow.com/questions/48266678/how-to-get-the-content-length-of-the-response-from-a-request-with-fetch

**Comment by dptolle** [comment]
Can't send the content-length header when using compression: https://www.npmjs.com/package/compression
