### ISSUE TITLE
Check if AB Resistance group by includes only positives

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/zoonotify-api#166]

**Comment by MicheleK17** [comment]
group-by=resistance only shows positives

http://localhost:3000/v1/isolate/counted?microorganism=CARBA-E.+coli
> Displays only resistances with "active": true

http://localhost:3000/v1/isolate/counted?microorganism=Campylobacter+spp.&campy_spez=C.+hyointestinalis&group-by=resistance
> Displays only resistances with "active": true

http://localhost:3000/v1/isolate/counted?microorganism=Campylobacter+spp.&resistance__Campylobacter+spp.=ERY&group-by=resistance
> Displays only resistances with "active": true
