### ISSUE TITLE
As a user I want the API documentation for the isolate endpoints to be available

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/zoonotify-api#44]
Define the endpoint for issue raw data download and issue statistics in the API documentation

**Comment by MicheleK17** [comment]
The API docs and the isolate API response do not match yet. In the response there is no id and "federalState" is called " state".

**Comment by MicheleK17** [comment]
There is a typo in the isolate/counted API doc 
firstAtributet => firstAttribute
secondAtributet => secondAttribute
